### ISSUE TITLE
Duo crash 

### ISSUE THREAD

**Issue by aigue15** [Muirey03/Duo#1] opened 2018-07-24 18:18 UTC
Hi, after installing duo my settings started to crash and duo can not add anything to the second page

**Comment by Muirey03** [comment] 2018-07-24 19:00
Please could you attach the crash log. Also, what ios/device are you using?

**Comment by aigue15** [comment] 2018-07-24 19:14
[archive (1).zip](https://github.com/Muirey03/Duo/files/2225022/archive.1.zip)
Here you can find the crash log of the settings. I use an Iphone 6s iOS 11.1.2

**Comment by aigue15** [comment] 2018-07-24 21:35
![Image](https://i.imgur.com/wOHpxnS.jpg)

I was able to find how to reproduce the crash when I try to give the modules a new order the settings crashes. Then there is this too as you can see in the image the music module does not fit the majority of it is outside of the screen.

**Comment by Muirey03** [comment] 2018-07-25 07:08
The second screenshot is not a bug, that's just how you've arranged your modules. I will look into the settings crash.

**Comment by Muirey03** [comment] 2018-07-28 08:59
Fixed in v.1.0.2

**Closed by Muirey03** 2018-07-28 08:59 UTC
